name: Deploy Website

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - "website/**"
      - ".github/**"
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "website/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd website && pnpm install --frozen-lockfile

      - name: Build
        run: cd website && pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/dist
          branch: gh-pages
