name: Fetch Properties

on:
  schedule:
    # Run every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fetch properties
        run: node dist/index.js
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
