name: Fetch Properties

on:
  schedule:
    # Run every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Fetch properties
        run: node dist/index.js
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          TGBOT_API: ${{ secrets.TGBOT_API }}
          TGCHAT_ID: ${{ secrets.TGCHAT_ID }}
          # USER_ID: ${{ secrets.USER_ID }}
